@echo off
echo Setting correct system PATH for dev server...
set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;%PATH%
echo Starting Next.js Dev Server...
npm run dev
